name: QA Web Automation Pipeline (Stable)

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
  schedule:
    - cron: "50 9 * * *"   # ทุกวัน 09:00 เวลาไทย

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # =========================
    # 1. Python setup
    # =========================
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    # =========================
    # 2. Install dependencies
    # =========================
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install robotframework-pabot

    # =========================
    # 3. Install Chrome
    # =========================
    - name: Install Chrome
      run: |
        sudo apt-get update
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        google-chrome --version

    # =========================
    # 4. Fix Linux / Chrome CI crash
    # =========================
    - name: Install system dependencies
      run: |
        sudo apt-get install -y \
          libnss3 \
          libgbm1 \
          libasound2t64 \
          libatk-bridge2.0-0 \
          libgtk-3-0

    - name: Fix /dev/shm for Chrome
      run: |
        sudo mount -o remount,size=2G /dev/shm

    # =========================
    # 5. Run tests
    # =========================
    - name: Run Robot Tests
      run: |
        python3 -m robot --variable DB_ENV:dev --variable BROWSER:chrome tests/

    # =========================
    # 6. Upload report
    # =========================
    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: robot-report
        path: results/
