name: QA Web Automation Pipeline
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"

jobs:

  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # =========================
    # 1. Python setup
    # =========================
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    # =========================
    # 2. Install dependencies
    # =========================
    - name: Install Python libs
      run: |
        pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install robotframework-pabot

    # =========================
    # 3. Install Chrome
    # =========================
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        google-chrome --version

    # =========================
    # 4. Fix Chrome CI crash root causes
    # =========================
    - name: Install required Linux libs
      run: |
        sudo apt-get install -y \
          libnss3 \
          libgbm1 \
          libasound2t64 \
          libatk-bridge2.0-0 \
          libgtk-3-0

    - name: Fix shared memory
      run: |
        sudo mount -o remount,size=2G /dev/shm

    # =========================
    # 5. Run tests
    # =========================
    - name: Run Robot Framework Tests (Stable)
      run: |
        pabot --processes 1 \
          --outputdir results \
          --variable BROWSER:chrome \
          --variable CHROME_OPTIONS:"--headless=new --no-sandbox --disable-dev-shm-usage --disable-gpu --window-size=1920,1080" \
          tests/

    # =========================
    # 6. Upload report
    # =========================
    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: robot-report
        path: results/