name: QA Web Automation Pipeline

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:

  robot-web-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # =========================
    # 1. Setup Python
    # =========================
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    # =========================
    # 2. Install dependencies
    # =========================
    - name: Install Robot Framework
      run: |
        pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary

    # =========================
    # 3. Install Chrome
    # =========================
    - name: Install Chrome
      run: |
        sudo apt-get update
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        google-chrome --version

    # =========================
    # 4. Fix Chrome crash
    # =========================
    - name: Install Linux dependencies
      run: |
        sudo apt-get install -y \
          libnss3 \
          libgbm1 \
          libasound2t64 \
          libatk-bridge2.0-0 \
          libgtk-3-0

    - name: Fix /dev/shm issue
      run: |
        sudo mount -o remount,size=2G /dev/shm

    # =========================
    # 5. Run tests (STABLE)
    # =========================
    - name: Run Robot Tests
      run: |
        python3 -m robot \
          --outputdir results \
          --variable BROWSER:chrome \
          --variable OPTIONS:"--headless=new --no-sandbox --disable-dev-shm-usage --disable-gpu --window-size=1920,1080" \
          tests/

    # =========================
    # 6. Upload report
    # =========================
    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: robot-report
        path: results/