name: Robot Framework Web Automation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # =========================
    # 1. Setup Python (stable version)
    # =========================
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    # =========================
    # 2. Install Python libs
    # =========================
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary

    # =========================
    # 3. Install Chrome
    # =========================
    - name: Install Chrome
      run: |
        sudo apt-get update
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        google-chrome --version

    # =========================
    # 4. Fix Chrome crash (IMPORTANT)
    # =========================
    - name: Install Linux dependencies
      run: |
        sudo apt-get install -y \
          libnss3 \
          libgbm1 \
          libasound2t64 \
          libatk-bridge2.0-0 \
          libgtk-3-0

    - name: Fix /dev/shm issue
      run: |
        sudo mount -o remount,size=2G /dev/shm

    # =========================
    # 5. Run tests (STABLE MODE)
    # =========================
    - name: Run Robot Tests
      run: |
        python3 -m robot \
          --outputdir results \
          tests/

    # =========================
    # 6. Upload report
    # =========================
    - name: Upload Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-report
        path: results/