name: Robot Framework Web Automation

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  web-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps + Chrome
        run: |
          pip install -U pip robotframework robotframework-seleniumlibrary
          sudo apt-get update
          sudo apt-get install -y \
            wget libnss3 libgbm1 libasound2t64 \
            libatk-bridge2.0-0 libgtk-3-0
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
      - name: Run tests
        run: |
          python -m robot --outputdir results tests/
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-report
          path: results/